// 📌 影响范围：声明 NapCat 4.18.13 系统类 Action，并通过 API.Call 访问；不保存凭据或状态。
package onebot

const (
	ActionGetLoginInfo              Action = "get_login_info"
	ActionGetVersionInfo            Action = "get_version_info"
	ActionCanSendRecord             Action = "can_send_record"
	ActionCanSendImage              Action = "can_send_image"
	ActionGetStatus                 Action = "get_status"
	ActionGetCSRFToken              Action = "get_csrf_token"
	ActionGetCredentials            Action = "get_credentials"
	ActionGetDoubtFriendsAddRequest Action = "get_doubt_friends_add_request"
	ActionSetDoubtFriendsAddRequest Action = "set_doubt_friends_add_request"
	ActionGetGroupSystemMessage     Action = "get_group_system_msg"
	ActionGetPacketStatus           Action = "nc_get_packet_status"
	ActionSetRestart                Action = "set_restart"
	ActionCleanCache                Action = "clean_cache"
	ActionSetOnlineStatus           Action = "set_online_status"
	ActionGetRobotUINRange          Action = "get_robot_uin_range"
	ActionFetchCustomFace           Action = "fetch_custom_face"
	ActionFetchCustomFaceDetail     Action = "fetch_custom_face_detail"
	ActionAddCustomFace             Action = "add_custom_face"
	ActionDeleteCustomFace          Action = "delete_custom_face"
	ActionSetCustomFaceDescription  Action = "set_custom_face_desc"
	ActionSetInputStatus            Action = "set_input_status"
	ActionGetUserStatus             Action = "nc_get_user_status"
	ActionGetRKey                   Action = "get_rkey"
	ActionGetRKeyServer             Action = "get_rkey_server"
	ActionGetNCRKey                 Action = "nc_get_rkey"
	ActionGetMiniAppArk             Action = "get_mini_app_ark"
	ActionSendPacket                Action = "send_packet"
	ActionBotExit                   Action = "bot_exit"
	ActionGetCollectionList         Action = "get_collection_list"
)
